# AZURE DEVOPS PIPELINE CONFIGURATION FILE
# ---------------------------------------------------------
# Copyright (C) 2021 Nextpart Security Intelligence GmbH
# All rights reserved. - Proprietary and confidential

name: $(Date:yyyyMMdd)$(Rev:.r) - Base Images

trigger:
  branches:
    include: ["master"]

resources:
  repositories:
    - repository: templates
      type: git
      name: NEXTPART/TEMPLATE-AzurePipeline

variables:
  - group: docker
  - group: pipeline

pool: K8S-KANIKO

jobs:
  - job: ImageBuildAndPush
    variables:
      image: 'imagepullsecret-patcher'
      tag: '0.14.0'
      context: '.'
      dockerfile: 'Dockerfile'
    workspace:
      clean: all
    steps:
      - template: kaniko_container.azure-pipelines.yaml@templates